image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npm run dev

vscode:
  extensions:
    - esbenp.prettier-vscode
    - Prisma.prisma
    - dbaeumer.vscode-eslint
    - GitHub.copilot
    - GitHub.copilot-chat
    - sourcegraph.cody-ai
