packages:
  - 'apps/*'
  - 'packages/*'
  - 'chrome-extension'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
