name: CI
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Detect package manager
        id: pm
        shell: bash
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "manager=pnpm" >> "$GITHUB_OUTPUT"
          elif [ -f package-lock.json ]; then
            echo "manager=npm" >> "$GITHUB_OUTPUT"
          else
            echo "manager=npm" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies (pnpm)
        if: steps.pm.outputs.manager == 'pnpm'
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install --frozen-lockfile || pnpm install

      - name: Install dependencies (npm)
        if: steps.pm.outputs.manager == 'npm'
        run: |
          npm ci || npm install

      - name: Lint (if script exists)
        run: |
          npm run -s lint || echo "no lint script"

      - name: Build (if script exists)
        run: |
          npm run -s build || echo "no build script"

      - name: Test (if script exists)
        run: |
          npm -s run test || echo "no test script"